function thepapu ( )
    cart = engineLoadTXD("jesterpapuxD.txd")
    engineImportTXD (cart,559)
    car = engineLoadDFF("jesterxD.dff")
    engineReplaceModel(car, 559)
end

function ReplaceAll ( )
    dff = engineLoadDFF ( "exh_a_j.dff" )
    engineReplaceModel ( dff, 1065 )
    dff1 = engineLoadDFF ( "exh_c_j.dff" )
    engineReplaceModel ( dff1, 1066 )
    dff2 = engineLoadDFF ( "fbmp_a_j.dff" )
    engineReplaceModel ( dff2, 1160 )
    dff3 = engineLoadDFF ("fbmp_c_j.dff")
    engineReplaceModel (dff3, 1173 )
    dff4 = engineLoadDFF ("rbmp_a_j.dff")
    engineReplaceModel (dff4, 1159 )
    dff5 = engineLoadDFF ("rbmp_c_j.dff")
    engineReplaceModel (dff5, 1161)
    dff6 = engineLoadDFF ("rf_a_j.dff")
    engineReplaceModel (dff6,1067)
    dff7 = engineLoadDFF ("rf_c_j.dff")
    engineReplaceModel (dff7,1068)
    dff8 = engineLoadDFF ("spl_a_j_b.dff")
    engineReplaceModel(dff8,1162)
    dff9 = engineLoadDFF ("spl_c_j_b.dff")
    engineReplaceModel(dff9,1158)
    dff10 = engineLoadDFF("wg_l_a_j.dff")
    engineReplaceModel(dff10,1069)
    dff11 = engineLoadDFF("wg_l_c_j.dff")
    engineReplaceModel(dff11,1070)
    dff12 = engineLoadDFF("wg_r_a_j.dff")
    engineReplaceModel(dff12,1071)
    dff13 = engineLoadDFF("wg_r_c_j.dff")
    engineReplaceModel(dff13,1072)
end

addEventHandler("onClientResourceStart", getRootElement(), thepapu) 
addEventHandler("onClientResourceStart", getRootElement(), ReplaceAll) 